name: Workflow for Codecov example-java-maven
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install dependencies, run tests, and collect coverage
        run: gradle build
      - name: check path
        run: pwd
      - name: find file
        run: ls
      - name: check path
        run: cd build/reports
      - name: find file
        run: ls
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
